# Generated by Django 2.2.5 on 2019-09-07 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfBirth', models.DateField()),
                ('address', models.TextField()),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('fathersName', models.CharField(max_length=100)),
                ('mothersName', models.CharField(max_length=100)),
                ('sscRollNo', models.IntegerField(unique=True)),
                ('sscRegiNo', models.IntegerField(unique=True)),
                ('sscGPA', models.FloatField(unique=True)),
                ('hscRollNo', models.IntegerField(unique=True)),
                ('hscGPA', models.FloatField(unique=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
