# Generated by Django 2.2.5 on 2019-09-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190907_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hscGPA',
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dateOfBirth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fathersName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hscRollNo',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mothersName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sscGPA',
            field=models.FloatField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sscRegiNo',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sscRollNo',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
