# Generated by Django 2.2.5 on 2019-09-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190907_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hscGPA',
            field=models.FloatField(blank=True, null=True, unique=True),
        ),
    ]
