# Generated by Django 2.2.5 on 2019-09-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lastName',
        ),
    ]
