# Generated by Django 2.2.5 on 2019-09-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_profile_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fathersName',
            new_name='fullName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mothersName',
        ),
    ]
