# Generated by Django 2.2.5 on 2019-09-07 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissionnews', '0002_auto_20190420_0502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=512)),
                ('details', models.TextField(default='')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissionnews.University')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Discussion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(default='')),
                ('date_answered', models.DateTimeField(default=django.utils.timezone.now)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissionnews.Discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
